export const FETCH_GUARDIAN = "FETCH_GUARDIAN";
export const FETCH_PROCESSED_DATA = "FETCH_PROCESSED_DATA";
export const ARTICLE_TITLE = "ARTICLE_TITLE";
export const DISPLAY_TOGGLE = "DISPLAY_TOGGLE";
export const REQUEST_PROCESSED_DATA = "REQUEST_PROCESSED_DATA";
export const RECEIVE_PROCESSED_DATA = "RECEIVE_PROCESSED_DATA";
export const SEARCH_BAR_TOGGLE = "SEARCH_BAR_TOGGLE";
